Ensure >=1 arg; loop on hosts

diff --git a/bin/rsysupgrade b/bin/rsysupgrade
--- a/bin/rsysupgrade
+++ b/bin/rsysupgrade
@@ -2,14 +2,10 @@
 
 # Shortcut sysupgrade from a sysupgraded machine to upgrade another machine on LAN
 # Use ONLY after:
-#	(a) successfully doing sysupgrade on this machine
-#	(b) Making sure the remote host is the same arch!
-#	(c) If the remote is pre-6.5, you should really do a full manual
+#	(a) successfully doing sysupgrade on the local machine
+#	(b) If the remote is pre-6.5, you should really do a full manual
 #		upgrade; if not possible, be sure you've upgraded boot blocks to 6.5+
 #		(update installboot and /usr/mdec, then run installboot)
-# Be aware that sysupgrade will only fetch release OR snaps depending on what
-# you run it on, and 6.5 release did not include necessary functionality,
-# so you might have to upgrade manually the first time!
 # Don't run under doas because you dont want to ssh as root.
 # Lightly tested on i386 and amd64 - use at own risk!
 
@@ -18,21 +14,32 @@
 	exit
 }
 
-HOST=$1
+case $# in
+	0)	echo "Usage: $0 host [...]" >&2
+		exit 1;;
+esac
 
 LOCAL_ARCH=$(arch)
-REMOTE_ARCH=$(ssh ${HOST} arch)
-if [ ${LOCAL_ARCH} != "${REMOTE_ARCH}" ]; then
-	echo "This machine is ${LOCAL_ARCH} but ${HOST} is ${REMOTE_ARCH}" >&2
-	exit 1;
-fi
 
-D=/home/_sysupgrade
+for HOST
+do
 
-set -e
+	REMOTE_ARCH=$(ssh ${HOST} arch)
+	if [ ${LOCAL_ARCH} != "${REMOTE_ARCH}" ]; then
+		echo "This machine is ${LOCAL_ARCH} but ${HOST} is ${REMOTE_ARCH}" >&2
+		exit 1;
+	fi
 
-ssh ${HOST} "doas mkdir -p ${D}; doas chmod g+w ${D}"
+	D=/home/_sysupgrade
 
-scp ${D}/* ${HOST}:${D}
+	set -e
 
-ssh ${HOST} doas "cp ${D}/bsd.rd /bsd.upgrade && doas reboot"
+	ssh ${HOST} "doas mkdir -p ${D}; doas chmod g+w ${D}"
+
+	scp ${D}/* ${HOST}:${D}
+
+	set +e # reboot will fail ssh
+
+	ssh ${HOST} doas "cp ${D}/bsd.rd /bsd.upgrade && doas reboot"
+
+done
