Modernize a bit, add -r remotehost option, checking to make sure we don't mess up localhost with wrong -a.

diff --git a/quickupgrade b/quickupgrade
--- a/quickupgrade
+++ b/quickupgrade
@@ -17,6 +17,7 @@ REL=48				# "46" for OpenBSD 4.6, etc.
 RELDIR=`echo $REL | sed -e 's/./&./'`	# e.g., "4.6" etc.
 SNAPDIR=snapshots
 DIR=${SNAPDIR}
+REMOTEHOST=localhost
 
 EXT=tgz
 
@@ -33,13 +34,14 @@ function usage {		# give usage message, and exit
 	[-e]	exec format has changed, backup executables first
 	[-k]	include kernel [don't]
 	[-p]	prefix for finding download files [/usr/download || ~ftp]
+	[-r remoteHost] Ssh upgrade (requires sudo access there)
 	[-s]	use snapshot [use release]
 	[-x]	include X11 [don't]
 	[-m]	Run sysmerge when done [don't] (requires full /usr/src)" 2>&1
 	exit 1
 }
 
-while getopts "a:bd:ekmp:rsxv" opt 
+while getopts "a:bd:ekmp:r:sxv" opt 
 do 
  	 case "$opt" in 
 		a)	ARCH=${OPTARG};;
@@ -49,6 +51,7 @@ do
 		k)	KERNEL=YES;;
 		m)	MERGEMASTER=YES;;
 		p)	DOWNLOAD=${OPTARG};;
+		r)	REMOTEHOST=${OPTARG};;
 		s)	DIR=${RELDIR};;	# stable, not snapshots
 		x)	X=YES;;
 		v)	VERBOSE='v';;
@@ -57,6 +60,11 @@ do
 done
 shift `expr $OPTIND - 1`		 # leave just filenames
 
+if [ ${REMOTEHOST} = localhost -a ${ARCH} != $(uname -m) ]; then
+	echo "$0: FAIL: localhost is not a ${ARCH}, you nimmie!"
+	exit 42
+fi
+
 if [ -d ${DOWNLOAD}/${DIR}/${ARCH} ]; then
 	cd ${DOWNLOAD}/${DIR}/${ARCH} || exit
 elif [ -d ~ftp/pub/OpenBSD/${DIR}/${ARCH} ]; then
@@ -64,13 +72,13 @@ elif [ -d ~ftp/pub/OpenBSD/${DIR}/${ARCH} ]; then
 fi
 
 # Check this AFTER getopts so -h works without sudo
-if [ ! -w ${DEST} ]; then
+if [ ${REMOTEHOST} = localhost -a ! -w ${DEST} ]; then
 	echo "$0: Need write permission on ${DEST}"
 	exit 1
 fi
 
 ls -l 
-echo -n "quickupgrade ${DIR}/${REL} on `hostname` from ${PWD}? [nyq]"
+echo -n "quickupgrade from ${PWD} on `hostname` to ${DEST} on ${REMOTEHOST}? [nyq]"
 read ans
 case ${ans} in
 	y*)	;;
@@ -78,7 +86,7 @@ case ${ans} in
 esac
 
 # NEVER include etc in this list, or you will die horribly!
-BDIRS="base comp misc man"
+BDIRS="base comp man" # misc is no more.
 XDIRS="xbase xfont xserv xshare"
 DIRS=""
 if [ "NO" != ${BASE} ]; then
@@ -88,18 +96,21 @@ if [ "YES" = ${X} ]; then
 	DIRS="${DIRS} ${XDIRS}"
 fi
 
-case ${BACKUP} in
-	YES)
+if [ ${BACKUP} = YES -a ${REMOTEHOST} = localhost ]; then
 		for dir in /bin /usr/bin /sbin /usr/sbin
 		do echo "Backing up $dir..."
 			cp -r $dir $dir.backup
 			PATH=$dir.backup:$PATH
 		done
+fi
+
+# This one backup step we do anyway, just in case
+case ${REMOTEHOST} in
+	localhost) cp /sbin/reboot /sbin/oreboot;;
+	*) 	echo "==> bkup reboot"
+		ssh ${REMOTEHOST} sudo cp /sbin/reboot /sbin/oreboot
 		;;
 esac
-# This one backup step we do anyway, just in case
-cp /sbin/reboot /sbin/oreboot
-
 
 for f in ${DIRS}
 do
@@ -110,12 +121,18 @@ do
 		echo "Cannot locate file ${FILE}"
 		exit
 	fi
-	(cd ${DEST} || exit; tar xzpf${VERBOSE} - ) < ${FILE}
+	case ${REMOTEHOST} in
+		localhost) (cd ${DEST} || exit; tar xzpf${VERBOSE} - ) < ${FILE};;
+		*) ssh ${REMOTEHOST} "(cd ${DEST} || exit; sudo tar xzpvf${VERBOSE} -)" < ${FILE}
+	esac
 done
 
 if [ "$KERNEL" = "YES" ]; then
 	if [ -f bsd ]; then
-		cp bsd ${DEST}/nbsd && echo Kernel installed as ${DEST}/nbsd
+		case ${REMOTEHOST} in
+			localhost) cp bsd ${DEST}/nbsd && echo Kernel installed as ${DEST}/nbsd;;
+			*) ssh ${REMOTEHOST} sudo cp bsd ${DEST}/nbsd && echo Kernel installed as ${DEST}/nbsd;;
+		esac
 	else
 		echo "File ./bsd not found, not installing /bsd" >&2
 	fi
@@ -124,12 +141,13 @@ else
 fi
 
 echo "Rebuilding /dev..."
-cd ${DEST}/dev
-sh MAKEDEV all
+case "${REMOTEHOST}" in
+localhost) cd ${DEST}/dev; sh MAKEDEV all;;
+*) ssh ${REMOTEHOST) "cd ${DEST}/dev; sudo sh MAKEDEV all";;
+esac
 
 if [ "$MERGEMASTER" = "YES" ]; then
-	(cd /tmp; tar xzpf - ) < etc${REL}.tgz
-	sysmerge
+	sysmerge -f etc${REL}.tgz
 else
 	echo "No -m, not running sysmerge" >&2
 fi
