Rewrite using getopt, add mergemaster run at end

diff --git a/quickupgrade b/quickupgrade
--- a/quickupgrade
+++ b/quickupgrade
@@ -1,17 +1,61 @@
-#!/bin/sh
+#!/bin/sh -u
 
 # quickupdate -- quickly update base files from snapshot
 
-REL=29				# "26" for OpenBSD 2.6, etc.
-RELDIR=2.9			# same but with a dot
+if [ ! -w / ]; then
+	echo "$0: Need root permission to run"
+	exit 1
+fi
+
+# Set defaults before getopt...
+
+ARCH=i386
+
+DEST=/
+
+# NEVER include etc in this list, or you will die horribly!
+BDIRS="base comp misc man"
+XDIRS="xbase xfont xserv xshare"
+DIRS="${BDIRS}"
+
+KERNEL=NOT
+
+MERGEMASTER=NOT
+
+REL=30				# "26" for OpenBSD 2.6, etc.
+RELDIR=3.0			# same but with a dot
 RELDIR=snapshots	# when not -stable
+
 case ${REL} in
 	2[0-6])		EXT=tar.gz;;
 	2[789]|3*)	EXT=tgz;;
 esac
 
-#ARCH=sparc
-ARCH=i386
+USAGE="$0 [-a arch][-x][-k][-m]"
+
+function usage {		# give usage message, and exit
+	echo "Usage: $USAGE
+	[-d dest]	Desination dir [${DEST}]
+	[-a arch]	i386, sparc, etc. [${ARCH}]
+	[-k]	include kernel [don't]
+	[-x]	include X11 [don't]
+	[-m]	Run MergeMaster when done [don't]" 2>&1
+	exit 1
+}
+
+while getopts "adkmx" opt 
+do 
+ 	 case "$opt" in 
+		a)	ARCH=${OPTARG};;
+		d)	DEST=${OPTARG};;
+		k)	KERNEL=YES;;
+		m)	MERGEMASTER=YES;;
+		x)	BDIRS="${BDIRS} ${XDIRS}";;
+		*)	usage;;
+	esac
+done
+shift `expr $OPTIND - 1`		 # leave just filenames
+
 
 if [ -d /usr/download/OpenBSD/${RELDIR}/${ARCH} ]; then
 	 cd /usr/download/OpenBSD/${RELDIR}/${ARCH} || exit
@@ -19,16 +63,6 @@ elif [ -d ~ftp/pub/OpenBSD/${RELDIR}/${ARCH} ]; then
 	 cd ~ftp/pub/OpenBSD/${RELDIR}/${ARCH} || exit
 fi
 
-DEST=/
-#DEST=/export/dartboard/root
-
-# NEVER include etc in this list, or you will die horribly!
-BDIRS="base comp misc man"
-XDIRS="xbase xfont xserv xshare"
-
-#DIRS="${BDIRS}"
-DIRS="${BDIRS} ${XDIRS}"
-#DIRS="${XDIRS}"
 
 for f in ${DIRS}
 do
@@ -39,11 +73,26 @@ do
 		echo "Cannot locate file ${FILE}"
 		exit
 	fi
-	(cd ${DEST} || exit; sudo tar xvzpf - ) < ${FILE}
+	(cd ${DEST} || exit; tar xvzpf - ) < ${FILE}
 done
 
-if [ -f bsd ]; then
-	sudo cp bsd ${DEST}/nbsd && echo Kernel installed as /nbsd
+if [ "$KERNEL" = "YES" ]; then
+	if [ -f bsd ]; then
+		cp bsd ${DEST}/nbsd && echo Kernel installed as /nbsd
+	else
+		echo "File ./bsd not found, not installing /bsd" >&2
+	fi
+else
+	echo "No -k argument, not installing kernel." >&2
 fi
 
 echo "*** REMEMBER TO RUN POSTUPGRADE ***"
+
+if [ "$MERGEMASTER" = "YES" ]; then
+	cp ./etc${REL}.${EXT} /tmp
+	cd /tmp
+	tar xzf ./etc${REL}.${EXT}
+	mergemaster -m ./etc
+else
+	echo "No -m, not running mergemaster" >&2
+fi
